#
# Copyright (C) 2007, Guennadi Liakhovetski <lg@denx.de>
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

ccflags-$(CONFIG_TURING_SMART_VARIANT) += -DTURING_SMART_VARIANT
obj-y  := mx6turing.o
